baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Welcome to Dave's Personal Blog"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
title = "Dave's Blog"
author = "David Coleman"
description = "Hello From Dave"

[menu]
[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"
